---
- hosts:
    - k8s_masters
  gather_facts: true
  become: true
  pre_tasks:
    - name: variables
      ansible.builtin.include_vars: vars/all.yml
    - name: Jenkins Deployment
      ansible.builtin.include_tasks: tasks/jenkins_helm.yaml
